from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profil-sekolah/', views.profil_sekolah, name='profil_sekolah'),
    path('data-guru/', views.data_guru, name='data_guru'),
    path('tambah-guru/', views.tambah_guru, name='tambah_guru'),
    path('data-murid/', views.data_murid, name='data_murid'),
    path('tambah-murid/', views.tambah_murid, name='tambah_murid'),
    path('data-aset/', views.data_aset, name='data_aset'),
    path('tambah-aset/', views.tambah_aset, name='tambah_aset'),
    path('edit-guru/<int:id>/', views.edit_guru, name='edit_guru'),
    path('hapus-guru/<int:id>/', views.hapus_guru, name='hapus_guru'),
    path('edit-murid/<int:id>/', views.edit_murid, name='edit_murid'),
    path('hapus-murid/<int:id>/', views.hapus_murid, name='hapus_murid'),
    path('edit-aset/<int:id>/', views.edit_aset, name='edit_aset'),
    path('hapus-aset/<int:id>/', views.hapus_aset, name='hapus_aset'),
    path('data-prestasi/', views.data_prestasi, name='data_prestasi'),
    path('tambah-prestasi/', views.tambah_prestasi, name='tambah_prestasi'),
    path('edit-prestasi/<int:id>/', views.edit_prestasi, name='edit_prestasi'),
    path('hapus-prestasi/<int:id>/', views.hapus_prestasi, name='hapus_prestasi'),
    path('tambah-sekolah/', views.tambah_sekolah, name='tambah_sekolah'),
    path('edit-sekolah/<int:id>/', views.edit_sekolah, name='edit_sekolah'),
    path('hapus-sekolah/<int:id>/', views.hapus_sekolah, name='hapus_sekolah'),    
    path('data-sekolah/', views.data_sekolah, name='data_sekolah'),
    path('tambah-user-operator/', views.tambah_user_operator, name='tambah_user_operator'),
    path('data-operator/', views.data_operator, name='data_operator'),
    path('tambah-user-admin-kecamatan/', views.tambah_user_admin_kecamatan, name='tambah_user_admin_kecamatan'),
    path('data-admin-kecamatan/', views.data_admin_kecamatan, name='data_admin_kecamatan'),
    path('tambah-user-admin-kabupaten/', views.tambah_user_admin_kabupaten, name='tambah_user_admin_kabupaten'),
    path('edit-operator/<int:id>/', views.edit_operator, name='edit_operator'),
    path('hapus-operator/<int:id>/', views.hapus_operator, name='hapus_operator'),
    path('edit-admin-kecamatan/<int:id>/', views.edit_admin_kecamatan, name='edit_admin_kecamatan'),
    path('hapus-admin-kecamatan/<int:id>/', views.hapus_admin_kecamatan, name='hapus_admin_kecamatan'),
    path('data-admin-kabupaten/', views.data_admin_kabupaten, name='data_admin_kabupaten'),
    path('edit-admin-kabupaten/<int:id>/', views.edit_admin_kabupaten, name='edit_admin_kabupaten'),
    path('hapus-admin-kabupaten/<int:id>/', views.hapus_admin_kabupaten, name='hapus_admin_kabupaten'),
]