# Generated by Django 6.0.5 on 2026-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('npsn', models.CharField(max_length=50, unique=True)),
                ('jenjang', models.CharField(choices=[('PAUD', 'PAUD'), ('TK', 'TK'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=20)),
                ('status', models.CharField(choices=[('Negeri', 'Negeri'), ('Swasta', 'Swasta')], max_length=20)),
                ('alamat', models.TextField()),
                ('kecamatan', models.CharField(max_length=100)),
                ('desa', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('jumlah_murid', models.IntegerField(default=0)),
                ('jumlah_guru', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sekolah/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
