# Generated by Django 6.0.5 on 2026-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='x_utm',
            field=models.FloatField(default=0, verbose_name='Easting / X UTM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sekolah',
            name='y_utm',
            field=models.FloatField(default=0, verbose_name='Northing / Y UTM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sekolah',
            name='zona_utm',
            field=models.CharField(default='50N', max_length=10),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
