# Generated by Django 6.0.5 on 2026-05-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_sekolah_x_utm_sekolah_y_utm_sekolah_zona_utm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('warna_marker', models.CharField(default='blue', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sekolah',
            name='jenjang',
        ),
        migrations.AddField(
            model_name='sekolah',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sekolah', to='sekolah.kategorisekolah'),
            preserve_default=False,
        ),
    ]
