# Generated by Django 6.0.5 on 2026-05-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_kategorisekolah_remove_sekolah_jenjang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekolah_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
