# Generated by Django 6.0.5 on 2026-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_sekolah_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
