# Generated by Django 6.0.5 on 2026-05-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_kecamatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='kecamatan_relasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekolah', to='sekolah.kecamatan'),
        ),
    ]
