# Generated by Django 6.0.5 on 2026-05-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_sekolah_kecamatan_relasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sekolah',
            name='kecamatan_relasi',
        ),
    ]
