# Generated by Django 6.0.5 on 2026-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_remove_sekolah_kecamatan_relasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='npsn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
