# Generated by Django 6.0.5 on 2026-05-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
        ('sekolah', '0004_sekolah_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.sekolah'),
        ),
    ]
