# Generated by Django 6.0.5 on 2026-05-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0003_kategorisekolah_remove_sekolah_jenjang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.CharField(blank=True, max_length=50, null=True)),
                ('nik', models.CharField(blank=True, max_length=30, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jabatan', models.CharField(max_length=100)),
                ('status_pegawai', models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'PPPK'), ('Honorer', 'Honorer'), ('GTY', 'GTY'), ('GTT', 'GTT')], max_length=30)),
                ('mata_pelajaran', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_pensiun', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to='sekolah.sekolah')),
            ],
        ),
    ]
