# Generated by Django 6.0.5 on 2026-08-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
        ('murid', '0006_alter_murid_nik_alter_murid_nisn'),
        ('sekolah', '0008_alter_sekolah_npsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nik', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nuptk', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pegawai',
                'verbose_name_plural': 'pegawai',
                'ordering': ('nama',),
            },
        ),
        migrations.CreateModel(
            name='RiwayatPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pegawai', models.CharField(choices=[('PENDIDIK', 'Guru / Pendidik'), ('TENAGA_KEPENDIDIKAN', 'Tenaga Kependidikan')], max_length=30)),
                ('jabatan', models.CharField(max_length=100)),
                ('mata_pelajaran', models.CharField(blank=True, max_length=100, null=True)),
                ('status_pegawai', models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'PPPK'), ('HONORER', 'Honorer'), ('GTY', 'GTY'), ('GTT', 'GTT')], max_length=30)),
                ('status_akhir', models.CharField(choices=[('AKTIF', 'Aktif'), ('MUTASI', 'Mutasi'), ('PENSIUN', 'Pensiun'), ('BERHENTI', 'Berhenti'), ('MENINGGAL', 'Meninggal')], default='AKTIF', max_length=30)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('tanggal_pensiun', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penempatan', to='guru.pegawai')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pegawai', to='sekolah.sekolah')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_pegawai', to='murid.tahunajaran')),
            ],
            options={
                'verbose_name': 'riwayat pegawai',
                'verbose_name_plural': 'riwayat pegawai',
                'ordering': ('-tahun_ajaran__nama', 'sekolah__nama', 'pegawai__nama'),
            },
        ),
        migrations.DeleteModel(
            name='Guru',
        ),
        migrations.AddConstraint(
            model_name='riwayatpegawai',
            constraint=models.UniqueConstraint(condition=models.Q(('status_akhir', 'AKTIF')), fields=('pegawai', 'tahun_ajaran'), name='unik_pegawai_aktif_per_tahun_ajaran'),
        ),
    ]
