# Generated by Django 6.0.5 on 2026-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20, unique=True)),
                ('aktif', models.BooleanField(default=False)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tahun ajaran',
                'verbose_name_plural': 'tahun ajaran',
                'ordering': ('-nama',),
            },
        ),
    ]
