# Generated by Django 6.0.5 on 2026-08-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0005_remove_datarombel_unik_nama_kelas_per_sekolah_and_more'),
        ('murid', '0002_tahunajaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatMurid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_masuk', models.CharField(choices=[('SISWA_BARU', 'Siswa Baru'), ('NAIK_KELAS', 'Naik Kelas'), ('TINGGAL_KELAS', 'Tinggal Kelas'), ('PINDAHAN', 'Siswa Pindahan'), ('LANJUT', 'Lanjutan')], default='SISWA_BARU', max_length=30)),
                ('status_akhir', models.CharField(choices=[('AKTIF', 'Aktif'), ('NAIK_KELAS', 'Naik Kelas'), ('TINGGAL_KELAS', 'Tinggal Kelas'), ('LULUS', 'Lulus'), ('PINDAH', 'Pindah'), ('KELUAR', 'Keluar')], default='AKTIF', max_length=30)),
                ('tahun_lulus', models.PositiveIntegerField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_akademik', to='murid.murid')),
                ('rombel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_murid', to='aset.datarombel')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_murid', to='murid.tahunajaran')),
            ],
            options={
                'verbose_name': 'riwayat murid',
                'verbose_name_plural': 'riwayat murid',
                'ordering': ('-tahun_ajaran__nama', 'rombel__nama_kelas', 'murid__nama'),
                'constraints': [models.UniqueConstraint(fields=('murid', 'tahun_ajaran'), name='unik_murid_per_tahun_ajaran')],
            },
        ),
    ]
