# Generated by Django 6.0.5 on 2026-08-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0003_riwayatmurid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahunajaran',
            name='tahun_sebelumnya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tahun_berikutnya', to='murid.tahunajaran'),
        ),
    ]
