# Generated by Django 6.0.5 on 2026-08-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0004_tahunajaran_tahun_sebelumnya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunajaran',
            name='tahun_sebelumnya',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tahun_berikutnya', to='murid.tahunajaran'),
        ),
    ]
