# Generated by Django 6.0.5 on 2026-08-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0005_alter_tahunajaran_tahun_sebelumnya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murid',
            name='nik',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='murid',
            name='nisn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
