DATA_WILAYAH = {
    'Muara Ancalong': [
        'Senyiur',
        'Kelinjau Ilir',
        'Kelinjau Ulu',
        'Long Nah',
        'Long Tesak',
        'Gemar Baru',
        'Long Poq Baru',
        'Muara Dun',
        'Teluk Baru',
    ],
    'Muara Wahau': [
        'Jak Luay',
        'Nehes Liah Bing',
        'Muara Wahau',
        'Dabeq',
        'Diaq Lay',
        'Benhes',
        'Wanasari',
        'Wahau Baru',
        'Karya Bhakti',
        'Long Wehea',
    ],
    'Muara Bengkal': [
        'Senambah',
        'Ngayau',
        'Muara Bengkal Ilir',
        'Muara Bengkal Ulu',
        'Benua Baru',
        'Mulupan',
        'Batu Balai',
    ],
    'Sangatta Utara': [
        'Sangatta Utara',
        'Kelurahan Teluk Lingga',
        'Singa Gembara',
        'Swarga Bara',
    ],
    'Sangkulirang': [
        'Kerayaan',
        'Tanjung Manis',
        'Peridan',
        'Saka',
        'Mandu Dalam',
        'Benua Baru Ilir',
        'Sempayau',
        'Pelawan',
        'Tepian Terap',
        'Maloy',
        'Benua Baru Ulu',
        'Kolek',
        'Pulau Miang',
        'Perupuk',
        'Mandu Pantai Sejahtera',
    ],
    'Busang': [
        'Long Bentuq',
        'Long Pejeng',
        'Long Lees',
        'Mekar Baru',
        'Rantau Sentosa',
        'Long Nyelong',
    ],
    'Telen': [
        'Marah Haloq',
        'Lung Melah',
        'Juk Ayaq',
        'Long Segar',
        'Long Noran',
        'Muara Pantun',
        'Rantau Panjang',
        'Kernyanyan',
    ],
    'Kombeng': [
        'Makmur Jaya',
        'Marga Mulya',
        'Suka Maju',
        'Sidomulyo',
        'Sri Pantun',
        'Kombeng Indah',
        'Miau Baru',
    ],
    'Bengalon': [
        'Sepaso',
        'Sekerat',
        'Keraitan',
        'Tepian Langsat',
        'Tebangan Lembak',
        'Sepaso Timur',
        'Sepaso Selatan',
        'Muara Bengalon',
        'Tepian Baru',
        'Tepian Indah',
        'Sepaso Barat',
    ],
    'Kaliorang': [
        'Kaliorang',
        'Bukit Makmur',
        'Bukit Harapan',
        'Citra Manunggal Jaya',
        'Bangun Jaya',
        'Bumi Sejahtera',
        'Selangkau',
    ],
    'Sandaran': [
        'Sandaran',
        'Manubar',
        'Tadoan',
        'Marukangan',
        'Susuk Luar',
        'Susuk Dalam',
        'Tanjung Mangkaliat',
        'Manubar Dalam',
        'Susuk Tengah',
    ],
    'Sangatta Selatan': [
        'Sangatta Selatan',
        'Kelurahan Singa Geweh',
        'Sangkima',
        'Teluk Singkama',
    ],
    'Teluk Pandan': [
        'Teluk Pandan',
        'Suka Rahmat',
        'Suka Damai',
        'Kandolo',
        'Danau Redan',
        'Martadinata',
    ],
    'Rantau Pulung': [
        'Mukti Jaya',
        'Pulung Sari',
        'Margomulyo',
        'Rantau Makmur',
        'Manunggal Jaya',
        'Tanjung Labu',
        'Kebon Agung',
        'Tepian Makmur',
        'Masalap Raya',
    ],
    'Kaubun': [
        'Bumi Etam',
        'Bumi Rapak',
        'Bumi Jaya',
        'Cipta Graha',
        'Kadungan Jaya',
        'Pengadan Baru',
        'Mata Air',
        'Bukit Permata',
    ],
    'Karangan': [
        'Karangan Dalam',
        'Batu Lepoq',
        'Pengadan',
        'Baay',
        'Mukti Lestari',
        'Karangan Seberang',
        'Karangan Hilir',
    ],
    'Batu Ampar': [
        'Batu Timbau',
        'Beno Harapan',
        'Mugi Rahayu',
        'Mawai Indah',
        'Himba Lestari',
        'Telaga',
        'Batu Timbau Ulu',
    ],
    'Long Mesangat': [
        'Sika Makmur',
        'Segoy Makmur',
        'Mukti Utama',
        'Sumber Sari',
        'Melan',
        'Tanah Abang',
        'Sumber Agung',
    ],
}