# Generated by Django 6.0.5 on 2026-05-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0004_sekolah_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=0)),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Rusak Ringan', 'Rusak Ringan'), ('Rusak Berat', 'Rusak Berat')], max_length=30)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='aset/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aset', to='sekolah.sekolah')),
            ],
        ),
    ]
