# Generated by Django 6.0.5 on 2026-08-09 11:21

import aset.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0001_initial'),
        ('sekolah', '0007_remove_sekolah_kecamatan_relasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.SlugField(max_length=100, unique=True)),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('kategori', models.CharField(choices=[('BANGUNAN', 'Bangunan dan Ruangan'), ('SANITASI', 'Sanitasi dan Lingkungan'), ('PERLENGKAPAN', 'Barang dan Perlengkapan')], max_length=30)),
                ('satuan', models.CharField(default='unit', max_length=30)),
                ('aset_kritis', models.BooleanField(default=False, help_text='Aset yang sangat memengaruhi prioritas bantuan sekolah.')),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'jenis aset',
                'verbose_name_plural': 'master jenis aset',
                'ordering': ('kategori', 'urutan', 'nama'),
            },
        ),
        migrations.CreateModel(
            name='AsetSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ketersediaan', models.CharField(choices=[('ADA', 'Ada'), ('TIDAK_ADA', 'Tidak Ada')], default='TIDAK_ADA', max_length=15)),
                ('jumlah_baik', models.PositiveIntegerField(default=0)),
                ('jumlah_rusak_ringan', models.PositiveIntegerField(default=0)),
                ('jumlah_rusak_berat', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaris_aset', to='sekolah.sekolah')),
                ('jenis_aset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sekolah', to='aset.jenisaset')),
            ],
            options={
                'verbose_name': 'aset sekolah',
                'verbose_name_plural': 'aset sekolah',
                'ordering': ('jenis_aset__kategori', 'jenis_aset__urutan'),
            },
        ),
        migrations.CreateModel(
            name='DataTanahSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas_tanah_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Luas Tanah (m²)')),
                ('status_kepemilikan', models.CharField(blank=True, choices=[('MILIK_PEMERINTAH', 'Milik Pemerintah'), ('MILIK_YAYASAN', 'Milik Yayasan'), ('HIBAH', 'Hibah'), ('SEWA', 'Sewa'), ('PINJAM_PAKAI', 'Pinjam Pakai'), ('SENGKETA', 'Sengketa'), ('LAINNYA', 'Lainnya')], max_length=30)),
                ('legalitas', models.CharField(choices=[('ADA', 'Ada'), ('TIDAK_ADA', 'Tidak Ada')], default='TIDAK_ADA', max_length=15)),
                ('jenis_dokumen', models.CharField(blank=True, max_length=100)),
                ('nomor_dokumen', models.CharField(blank=True, max_length=150)),
                ('tanggal_dokumen', models.DateField(blank=True, null=True)),
                ('atas_nama', models.CharField(blank=True, max_length=150)),
                ('luas_dokumen_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Luas dalam Dokumen (m²)')),
                ('keterangan', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('sekolah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_tanah', to='sekolah.sekolah')),
            ],
            options={
                'verbose_name': 'data tanah sekolah',
                'verbose_name_plural': 'data tanah sekolah',
            },
        ),
        migrations.CreateModel(
            name='DataRombel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('jumlah_rombel', models.PositiveSmallIntegerField(default=1)),
                ('jumlah_siswa', models.PositiveIntegerField(default=0)),
                ('kapasitas_ideal', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rombel', to='sekolah.sekolah')),
            ],
            options={
                'verbose_name': 'data rombongan belajar',
                'verbose_name_plural': 'data rombongan belajar',
                'ordering': ('nama_kelas',),
                'constraints': [models.UniqueConstraint(fields=('sekolah', 'nama_kelas'), name='unik_nama_kelas_per_sekolah')],
            },
        ),
        migrations.CreateModel(
            name='DokumenTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=aset.models.lokasi_dokumen_tanah)),
                ('urutan', models.PositiveSmallIntegerField(default=1)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('data_tanah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='aset.datatanahsekolah')),
            ],
            options={
                'verbose_name': 'dokumen tanah',
                'verbose_name_plural': 'dokumen tanah',
                'ordering': ('urutan', 'id'),
                'constraints': [models.UniqueConstraint(fields=('data_tanah', 'urutan'), name='unik_urutan_dokumen_tanah'), models.CheckConstraint(condition=models.Q(('urutan__gte', 1), ('urutan__lte', 3)), name='urutan_dokumen_tanah_1_sampai_3')],
            },
        ),
        migrations.CreateModel(
            name='FotoAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=aset.models.lokasi_foto_aset)),
                ('urutan', models.PositiveSmallIntegerField(default=1)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('aset_sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_dokumentasi', to='aset.asetsekolah')),
            ],
            options={
                'verbose_name': 'foto aset',
                'verbose_name_plural': 'foto aset',
                'ordering': ('urutan', 'id'),
                'constraints': [models.UniqueConstraint(fields=('aset_sekolah', 'urutan'), name='unik_urutan_foto_aset'), models.CheckConstraint(condition=models.Q(('urutan__gte', 1), ('urutan__lte', 3)), name='urutan_foto_aset_1_sampai_3')],
            },
        ),
        migrations.AddConstraint(
            model_name='asetsekolah',
            constraint=models.UniqueConstraint(fields=('sekolah', 'jenis_aset'), name='unik_aset_per_sekolah'),
        ),
        migrations.AddConstraint(
            model_name='asetsekolah',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('jumlah_baik', 0), ('jumlah_rusak_berat', 0), ('jumlah_rusak_ringan', 0), ('ketersediaan', 'TIDAK_ADA')), models.Q(('ketersediaan', 'ADA'), models.Q(('jumlah_baik__gt', 0), ('jumlah_rusak_ringan__gt', 0), ('jumlah_rusak_berat__gt', 0), _connector='OR')), _connector='OR'), name='ketersediaan_sesuai_jumlah_aset'),
        ),
    ]
