# Generated by Django 6.0.5 on 2026-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0003_isi_master_jenis_aset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asetsekolah',
            name='sudah_diisi',
            field=models.BooleanField(default=False, verbose_name='Sudah Diisi'),
        ),
    ]
