# Generated by Django 6.0.5 on 2026-08-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0004_asetsekolah_sudah_diisi'),
        ('murid', '0002_tahunajaran'),
        ('sekolah', '0008_alter_sekolah_npsn'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datarombel',
            name='unik_nama_kelas_per_sekolah',
        ),
        migrations.AddField(
            model_name='datarombel',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_rombel', to='murid.tahunajaran'),
        ),
        migrations.AddConstraint(
            model_name='datarombel',
            constraint=models.UniqueConstraint(fields=('sekolah', 'nama_kelas', 'tahun_ajaran'), name='unik_nama_kelas_per_sekolah_tahun'),
        ),
    ]
