# Generated by Django 6.0.5 on 2026-08-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0005_remove_datarombel_unik_nama_kelas_per_sekolah_and_more'),
        ('murid', '0005_alter_tahunajaran_tahun_sebelumnya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarombel',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_rombel', to='murid.tahunajaran'),
        ),
    ]
