# Generated by Django 6.0.5 on 2026-08-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0006_alter_datarombel_tahun_ajaran'),
        ('sekolah', '0008_alter_sekolah_npsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangTanahSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_bidang', models.PositiveIntegerField(verbose_name='Nomor Bidang')),
                ('luas_bidang_m2', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Luas Bidang (m²)')),
                ('status_kepemilikan', models.CharField(choices=[('PEMDA', 'Milik Pemerintah Daerah'), ('PEMERINTAH_PUSAT', 'Milik Pemerintah Pusat'), ('YAYASAN', 'Milik Yayasan'), ('HIBAH_PEMDA', 'Hibah kepada Pemerintah Daerah'), ('HIBAH_SEKOLAH', 'Hibah kepada Sekolah'), ('PINJAM_PAKAI', 'Pinjam Pakai'), ('SEWA', 'Sewa'), ('PENGUASAAN', 'Penguasaan'), ('LAINNYA', 'Lainnya')], max_length=30, verbose_name='Status Kepemilikan')),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bidang tanah sekolah',
                'verbose_name_plural': 'bidang tanah sekolah',
                'ordering': ['nomor_bidang'],
            },
        ),
        migrations.CreateModel(
            name='LegalitasTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(choices=[('SERTIFIKAT', 'Sertifikat Tanah'), ('SPPT', 'Surat Pernyataan Penguasaan Tanah'), ('HIBAH', 'Surat Hibah'), ('AKTA_HIBAH', 'Akta Hibah'), ('BAST', 'Berita Acara Serah Terima'), ('PINJAM_PAKAI', 'Perjanjian Pinjam Pakai'), ('SEWA', 'Perjanjian Sewa'), ('SKT', 'Surat Keterangan Tanah'), ('LAINNYA', 'Dokumen Lainnya')], max_length=30)),
                ('nama_dokumen', models.CharField(blank=True, max_length=150, verbose_name='Nama Dokumen')),
                ('nomor_dokumen', models.CharField(blank=True, max_length=150, verbose_name='Nomor Dokumen')),
                ('tanggal_dokumen', models.DateField(blank=True, null=True, verbose_name='Tanggal Dokumen')),
                ('atas_nama', models.CharField(blank=True, max_length=150, verbose_name='Atas Nama')),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'legalitas tanah',
                'verbose_name_plural': 'legalitas tanah',
                'ordering': ['-tanggal_dokumen', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='datatanahsekolah',
            name='sekolah',
        ),
        migrations.AlterModelOptions(
            name='dokumentanah',
            options={'ordering': ['id'], 'verbose_name': 'dokumen tanah', 'verbose_name_plural': 'dokumen tanah'},
        ),
        migrations.RemoveConstraint(
            model_name='dokumentanah',
            name='unik_urutan_dokumen_tanah',
        ),
        migrations.RemoveConstraint(
            model_name='dokumentanah',
            name='urutan_dokumen_tanah_1_sampai_3',
        ),
        migrations.AddField(
            model_name='dokumentanah',
            name='nama_file',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bidangtanahsekolah',
            name='sekolah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidang_tanah', to='sekolah.sekolah'),
        ),
        migrations.AddField(
            model_name='legalitastanah',
            name='bidang_tanah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalitas', to='aset.bidangtanahsekolah'),
        ),
        migrations.AddField(
            model_name='dokumentanah',
            name='legalitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='aset.legalitastanah'),
        ),
        migrations.RemoveField(
            model_name='dokumentanah',
            name='data_tanah',
        ),
        migrations.RemoveField(
            model_name='dokumentanah',
            name='urutan',
        ),
        migrations.AddConstraint(
            model_name='bidangtanahsekolah',
            constraint=models.UniqueConstraint(fields=('sekolah', 'nomor_bidang'), name='unik_nomor_bidang_per_sekolah'),
        ),
        migrations.DeleteModel(
            name='DataTanahSekolah',
        ),
    ]
