# Generated by Django 6.0.5 on 2026-08-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0007_bidangtanahsekolah_legalitastanah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentanah',
            name='legalitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='aset.legalitastanah'),
        ),
    ]
