# Generated by Django 6.0.5 on 2026-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0008_alter_dokumentanah_legalitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarombel',
            name='tingkat',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Kelas 1'), (2, 'Kelas 2'), (3, 'Kelas 3'), (4, 'Kelas 4'), (5, 'Kelas 5'), (6, 'Kelas 6'), (7, 'Kelas 7'), (8, 'Kelas 8'), (9, 'Kelas 9')], null=True, verbose_name='Tingkat Kelas'),
        ),
    ]
