# Generated by Django 6.0.5 on 2026-05-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('murid', '0001_initial'),
        ('sekolah', '0004_sekolah_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lomba', models.CharField(max_length=255)),
                ('bidang_lomba', models.CharField(max_length=150)),
                ('tingkat', models.CharField(choices=[('Sekolah', 'Sekolah'), ('Kecamatan', 'Kecamatan'), ('Kabupaten', 'Kabupaten'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=50)),
                ('juara', models.CharField(choices=[('Juara 1', 'Juara 1'), ('Juara 2', 'Juara 2'), ('Juara 3', 'Juara 3'), ('Harapan 1', 'Harapan 1'), ('Harapan 2', 'Harapan 2'), ('Harapan 3', 'Harapan 3'), ('Peserta', 'Peserta')], max_length=50)),
                ('tahun', models.IntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('bukti_foto', models.ImageField(blank=True, null=True, upload_to='prestasi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_prestasi', to='murid.murid')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='sekolah.sekolah')),
            ],
        ),
    ]
